%table(class,[classid,"name","fields","methods",superid]).
table(class,c0,"WorkSpace"]).
table(class,c1,"Edge"]).
table(class,c2,"Vertex"]).
table(class,c3,"NumberWorkSpace"]).
table(class,c4,"Neighbor"]).
table(class,c5,"Main"]).
table(class,c6,"CycleWorkSpace"]).
table(class,c7,"Graph"]).
%table(attribute,[attrid,"name","type",classid]).
attribute(a0,'start','Vertex',c1).
attribute(a1,'weight','int',c1).
attribute(a10,'edge','Edge',c4).
attribute(a11,'AnyCycles','boolean',c6).
attribute(a12,'counter','int',c6).
attribute(a13,'isDirected','boolean',c6).
attribute(a14,'WHITE','int',c6).
attribute(a15,'GRAY','int',c6).
attribute(a16,'BLACK','int',c6).
attribute(a17,'isDirected','boolean',c7).
attribute(a18,'ch','int',c7).
attribute(a19,'last','long',c7).
attribute(a2,'neighbors','LinkedList',c2).
attribute(a20,'current','long',c7).
attribute(a21,'accum','long',c7).
attribute(a22,'vertices','LinkedList',c7).
attribute(a23,'edges','LinkedList',c7).
attribute(a24,'inFile','Reader',c7).
attribute(a3,'name','String',c2).
attribute(a4,'visited','boolean',c2).
attribute(a5,'VertexCycle','int',c2).
attribute(a6,'VertexColor','int',c2).
attribute(a7,'VertexNumber','int',c2).
attribute(a8,'vertexCounter','int',c3).
attribute(a9,'end','Vertex',c4).
%table(method,[methid,"name","returntype",classid]).
method(m0,'graff.WorkSpace','WorkSpace',c0).
method(m1,'init_vertex','WorkSpace',c0).
method(m10,'adjustAdorns','Edge',c1).
method(m11,'graff.Vertex','Vertex',c2).
method(m12,'init_vertex','Vertex',c2).
method(m13,'VertexConstructor','Vertex',c2).
method(m14,'addNeighbor','Vertex',c2).
method(m15,'assignName','Vertex',c2).
method(m16,'dftNodeSearch','Vertex',c2).
method(m17,'display','Vertex',c2).
method(m18,'graff.NumberWorkSpace','NumberWorkSpace',c3).
method(m19,'preVisitAction','NumberWorkSpace',c3).
method(m2,'preVisitAction','WorkSpace',c0).
method(m20,'graff.Neighbor','Neighbor',c4).
method(m21,'graff.Neighbor','Neighbor',c4).
method(m22,'graff.Main','Main',c5).
method(m23,'main','Main',c5).
method(m24,'graff.CycleWorkSpace','CycleWorkSpace',c6).
method(m25,'init_vertex','CycleWorkSpace',c6).
method(m26,'preVisitAction','CycleWorkSpace',c6).
method(m27,'postVisitAction','CycleWorkSpace',c6).
method(m28,'checkNeighborAction','CycleWorkSpace',c6).
method(m29,'graff.Graph','Graph',c7).
method(m3,'postVisitAction','WorkSpace',c0).
method(m30,'run','Graph',c7).
method(m31,'display','Graph',c7).
method(m32,'runBenchmark','Graph',c7).
method(m33,'readNumber','Graph',c7).
method(m34,'addVertex','Graph',c7).
method(m35,'stopBenchmark','Graph',c7).
method(m36,'addAnEdge','Graph',c7).
method(m37,'startProfile','Graph',c7).
method(m38,'findsVertex','Graph',c7).
method(m39,'stopProfile','Graph',c7).
method(m4,'nextRegionAction','WorkSpace',c0).
method(m40,'resumeProfile','Graph',c7).
method(m41,'endProfile','Graph',c7).
method(m42,'CycleCheck','Graph',c7).
method(m43,'GraphSearch','Graph',c7).
method(m44,'NumberVertices','Graph',c7).
method(m45,'addEdge','Graph',c7).
method(m46,'addOnlyEdge','Graph',c7).
method(m5,'checkNeighborAction','WorkSpace',c0).
method(m6,'graff.Edge','Edge',c1).
method(m7,'display','Edge',c1).
method(m8,'EdgeConstructor','Edge',c1).
method(m9,'EdgeConstructor','Edge',c1).
%table(parameter,[paramid,"type",methid]).
parameter(p0,'Vertex',m1).
parameter(p1,'Vertex',m2).
parameter(p10,'int',m9).
parameter(p11,'Edge',m10).
parameter(p12,'WorkSpace',m12).
parameter(p13,'Neighbor',m14).
parameter(p14,'String',m15).
parameter(p15,'WorkSpace',m16).
parameter(p16,'Vertex',m19).
parameter(p17,'Vertex',m21).
parameter(p18,'Edge',m21).
parameter(p19,'String[]',m23).
parameter(p2,'Vertex',m3).
parameter(p20,'boolean',m24).
parameter(p21,'Vertex',m25).
parameter(p22,'Vertex',m26).
parameter(p23,'Vertex',m27).
parameter(p24,'Vertex',m28).
parameter(p25,'Vertex',m28).
parameter(p26,'Vertex',m30).
parameter(p27,'String',m32).
parameter(p28,'Vertex',m34).
parameter(p29,'Vertex',m36).
parameter(p3,'Vertex',m4).
parameter(p30,'Vertex',m36).
parameter(p31,'int',m36).
parameter(p32,'String',m38).
parameter(p33,'WorkSpace',m43).
parameter(p34,'Edge',m45).
parameter(p35,'Edge',m46).
parameter(p4,'Vertex',m5).
parameter(p5,'Vertex',m5).
parameter(p6,'Vertex',m8).
parameter(p7,'Vertex',m8).
parameter(p8,'Vertex',m9).
parameter(p9,'Vertex',m9).
