%table(class,[classid,"name","fields","methods",superid]).
table(class,c0,"About"]).
table(class,c1,"Print"]).
table(class,c2,"UndoAction"]).
table(class,c3,"ExampleFileFilter"]).
table(class,c4,"Actions"]).
table(class,c5,"RedoAction"]).
table(class,c6,"Main"]).
table(class,c7,"Fonts"]).
table(class,c8,"Center"]).
%table(attribute,[attrid,"name","type",classid]).
attribute(a0,'componentToBePrinted','Component',c1).
attribute(a1,'notepad','Main',c2).
attribute(a10,'fileContent','String',c4).
attribute(a11,'fileName','String',c4).
attribute(a12,'findword','String',c4).
attribute(a13,'jfc','JFileChooser',c4).
attribute(a14,'filter','ExampleFileFilter',c4).
attribute(a15,'n','Main',c4).
attribute(a16,'font','Fonts',c4).
attribute(a17,'notepad','Main',c5).
attribute(a18,'actions','Actions',c6).
attribute(a19,'center','Center',c6).
attribute(a2,'TYPE_UNKNOWN','String',c3).
attribute(a20,'undo','UndoManager',c6).
attribute(a21,'undoAction','UndoAction',c6).
attribute(a22,'redoAction','RedoAction',c6).
attribute(a23,'textArea','JTextArea',c6).
attribute(a24,'Menubar','JMenuBar',c6).
attribute(a25,'filE','JMenu',c6).
attribute(a26,'ediT','JMenu',c6).
attribute(a27,'vieW','JMenu',c6).
attribute(a28,'formaT','JMenu',c6).
attribute(a29,'helP','JMenu',c6).
attribute(a3,'HIDDEN_FILE','String',c3).
attribute(a30,'neW','JMenuItem',c6).
attribute(a31,'opeN','JMenuItem',c6).
attribute(a32,'savE','JMenuItem',c6).
attribute(a33,'saveAS','JMenuItem',c6).
attribute(a34,'prinT','JMenuItem',c6).
attribute(a35,'exiT','JMenuItem',c6).
attribute(a36,'fonT','JMenuItem',c6).
attribute(a37,'abouT','JMenuItem',c6).
attribute(a38,'cuT','JMenuItem',c6).
attribute(a39,'copY','JMenuItem',c6).
attribute(a4,'filters','Hashtable',c3).
attribute(a40,'pastE','JMenuItem',c6).
attribute(a41,'selectALL','JMenuItem',c6).
attribute(a42,'finD','JMenuItem',c6).
attribute(a43,'findNexT','JMenuItem',c6).
attribute(a44,'lineWraP','JCheckBoxMenuItem',c6).
attribute(a45,'toolBar','JToolBar',c6).
attribute(a46,'newButton','JButton',c6).
attribute(a47,'openButton','JButton',c6).
attribute(a48,'saveButton','JButton',c6).
attribute(a49,'saveAsButton','JButton',c6).
attribute(a5,'description','String',c3).
attribute(a50,'printButton','JButton',c6).
attribute(a51,'undoButton','JButton',c6).
attribute(a52,'redoButton','JButton',c6).
attribute(a53,'cutButton','JButton',c6).
attribute(a54,'copyButton','JButton',c6).
attribute(a55,'pasteButton','JButton',c6).
attribute(a56,'findButton','JButton',c6).
attribute(a57,'fontButton','JButton',c6).
attribute(a58,'aboutButton','JButton',c6).
attribute(a59,'scrollpane','JScrollPane',c6).
attribute(a6,'fullDescription','String',c3).
attribute(a60,'center','Center',c7).
attribute(a61,'jp','JPanel',c7).
attribute(a62,'fjl','JLabel',c7).
attribute(a63,'fjcb','JComboBox',c7).
attribute(a64,'fonts','String[]',c7).
attribute(a65,'sjl','JLabel',c7).
attribute(a66,'sjcb','JComboBox',c7).
attribute(a67,'sizes','String[]',c7).
attribute(a68,'tjl','JLabel',c7).
attribute(a69,'tjcb','JComboBox',c7).
attribute(a7,'useExtensionsInDescription','boolean',c3).
attribute(a70,'types','String[]',c7).
attribute(a71,'jjl','JLabel',c7).
attribute(a72,'jl','JLabel',c7).
attribute(a73,'okjb','JButton',c7).
attribute(a74,'cajb','JButton',c7).
attribute(a75,'n','Main',c8).
attribute(a76,'f','Fonts',c8).
attribute(a8,'returnVal','int',c4).
attribute(a9,'option','int',c4).
%table(method,[methid,"name","returntype",classid]).
method(m0,'Notepad.About','About',c0).
method(m1,'Notepad.Print','Print',c1).
method(m10,'Notepad.ExampleFileFilter','ExampleFileFilter',c3).
method(m11,'Notepad.ExampleFileFilter','ExampleFileFilter',c3).
method(m12,'Notepad.ExampleFileFilter','ExampleFileFilter',c3).
method(m13,'Notepad.ExampleFileFilter','ExampleFileFilter',c3).
method(m14,'Notepad.ExampleFileFilter','ExampleFileFilter',c3).
method(m15,'accept','ExampleFileFilter',c3).
method(m16,'getExtension','ExampleFileFilter',c3).
method(m17,'addExtension','ExampleFileFilter',c3).
method(m18,'getDescription','ExampleFileFilter',c3).
method(m19,'setDescription','ExampleFileFilter',c3).
method(m2,'print','Print',c1).
method(m20,'setExtensionListInDescription','ExampleFileFilter',c3).
method(m21,'isExtensionListInDescription','ExampleFileFilter',c3).
method(m22,'Notepad.Actions','Actions',c4).
method(m23,'save','Actions',c4).
method(m24,'open','Actions',c4).
method(m25,'neW','Actions',c4).
method(m26,'opeN','Actions',c4).
method(m27,'savE','Actions',c4).
method(m28,'prinT','Actions',c4).
method(m29,'exiT','Actions',c4).
method(m3,'print','Print',c1).
method(m30,'fonT','Actions',c4).
method(m31,'abouT','Actions',c4).
method(m32,'cuT','Actions',c4).
method(m33,'copY','Actions',c4).
method(m34,'pastE','Actions',c4).
method(m35,'selectALL','Actions',c4).
method(m36,'finD','Actions',c4).
method(m37,'findNexT','Actions',c4).
method(m38,'lineWraP','Actions',c4).
method(m39,'saveAs','Actions',c4).
method(m4,'printComponent','Print',c1).
method(m40,'Notepad.RedoAction','RedoAction',c5).
method(m41,'update','RedoAction',c5).
method(m42,'actionPerformed','RedoAction',c5).
method(m43,'Notepad.Main','Main',c6).
method(m44,'main','Main',c6).
method(m45,'getLineWrap','Main',c6).
method(m46,'getTextArea','Main',c6).
method(m47,'Notepad.Fonts','Fonts',c7).
method(m48,'access$000','Fonts',c7).
method(m49,'access$200','Fonts',c7).
method(m5,'disableDoubleBuffering','Print',c1).
method(m50,'access$100','Fonts',c7).
method(m51,'font','Fonts',c7).
method(m52,'getOkjb','Fonts',c7).
method(m53,'getCajb','Fonts',c7).
method(m54,'Notepad.Center','Center',c8).
method(m55,'Notepad.Center','Center',c8).
method(m56,'nCenter','Center',c8).
method(m57,'fCenter','Center',c8).
method(m6,'enableDoubleBuffering','Print',c1).
method(m7,'Notepad.UndoAction','UndoAction',c2).
method(m8,'update','UndoAction',c2).
method(m9,'actionPerformed','UndoAction',c2).
%table(parameter,[paramid,"type",methid]).
parameter(p0,'Component',m1).
parameter(p1,'Graphics',m3).
parameter(p10,'String',m12).
parameter(p11,'String',m12).
parameter(p12,'String[]',m13).
parameter(p13,'String[]',m14).
parameter(p14,'String',m14).
parameter(p15,'File',m15).
parameter(p16,'File',m16).
parameter(p17,'String',m17).
parameter(p18,'String',m19).
parameter(p19,'boolean',m20).
parameter(p2,'PageFormat',m3).
parameter(p20,'Main',m22).
parameter(p21,'Main',m40).
parameter(p22,'ActionEvent',m42).
parameter(p23,'String[]',m44).
parameter(p24,'Fonts',m48).
parameter(p25,'Fonts',m49).
parameter(p26,'Fonts',m50).
parameter(p27,'Main',m54).
parameter(p28,'Fonts',m55).
parameter(p3,'int',m3).
parameter(p4,'Component',m4).
parameter(p5,'Component',m5).
parameter(p6,'Component',m6).
parameter(p7,'Main',m7).
parameter(p8,'ActionEvent',m9).
parameter(p9,'String',m11).
