%table(class,[classid,"name","fields","methods",superid]).
class(c0,"About").
class(c1,"Print").
class(c2,"UndoAction").
class(c3,"ExampleFileFilter").
class(c4,"Actions").
class(c5,"RedoAction").
class(c6,"Main").
class(c7,"Fonts").
class(c8,"Center").
%table(attribute,[attrid,"name","type",classid]).
attribute(a0,'componentToBePrinted','Component',c1).
attribute(a1,'notepad','Main',c2).
attribute(a10,'fileContent','String',c4).
attribute(a11,'fileName','String',c4).
attribute(a12,'findword','String',c4).
attribute(a13,'jfc','JFileChooser',c4).
attribute(a14,'filter','ExampleFileFilter',c4).
attribute(a15,'n','Main',c4).
attribute(a16,'font','Fonts',c4).
attribute(a17,'notepad','Main',c5).
attribute(a18,'actions','Actions',c6).
attribute(a19,'center','Center',c6).
attribute(a2,'TYPE_UNKNOWN','String',c3).
attribute(a20,'undo','UndoManager',c6).
attribute(a21,'undoAction','UndoAction',c6).
attribute(a22,'redoAction','RedoAction',c6).
attribute(a23,'textArea','JTextArea',c6).
attribute(a24,'Menubar','JMenuBar',c6).
attribute(a25,'filE','JMenu',c6).
attribute(a26,'ediT','JMenu',c6).
attribute(a27,'vieW','JMenu',c6).
attribute(a28,'formaT','JMenu',c6).
attribute(a29,'helP','JMenu',c6).
attribute(a3,'HIDDEN_FILE','String',c3).
attribute(a30,'neW','JMenuItem',c6).
attribute(a31,'opeN','JMenuItem',c6).
attribute(a32,'savE','JMenuItem',c6).
attribute(a33,'saveAS','JMenuItem',c6).
attribute(a34,'prinT','JMenuItem',c6).
attribute(a35,'exiT','JMenuItem',c6).
attribute(a36,'fonT','JMenuItem',c6).
attribute(a37,'abouT','JMenuItem',c6).
attribute(a38,'cuT','JMenuItem',c6).
attribute(a39,'copY','JMenuItem',c6).
attribute(a4,'filters','Hashtable',c3).
attribute(a40,'pastE','JMenuItem',c6).
attribute(a41,'selectALL','JMenuItem',c6).
attribute(a42,'finD','JMenuItem',c6).
attribute(a43,'findNexT','JMenuItem',c6).
attribute(a44,'lineWraP','JCheckBoxMenuItem',c6).
attribute(a45,'toolBar','JToolBar',c6).
attribute(a46,'newButton','JButton',c6).
attribute(a47,'openButton','JButton',c6).
attribute(a48,'saveButton','JButton',c6).
attribute(a49,'saveAsButton','JButton',c6).
attribute(a5,'description','String',c3).
attribute(a50,'printButton','JButton',c6).
attribute(a51,'undoButton','JButton',c6).
attribute(a52,'redoButton','JButton',c6).
attribute(a53,'cutButton','JButton',c6).
attribute(a54,'copyButton','JButton',c6).
attribute(a55,'pasteButton','JButton',c6).
attribute(a56,'findButton','JButton',c6).
attribute(a57,'fontButton','JButton',c6).
attribute(a58,'aboutButton','JButton',c6).
attribute(a59,'scrollpane','JScrollPane',c6).
attribute(a6,'fullDescription','String',c3).
attribute(a60,'center','Center',c7).
attribute(a61,'jp','JPanel',c7).
attribute(a62,'fjl','JLabel',c7).
attribute(a63,'fjcb','JComboBox',c7).
attribute(a64,'fonts','String[]',c7).
attribute(a65,'sjl','JLabel',c7).
attribute(a66,'sjcb','JComboBox',c7).
attribute(a67,'sizes','String[]',c7).
attribute(a68,'tjl','JLabel',c7).
attribute(a69,'tjcb','JComboBox',c7).
attribute(a7,'useExtensionsInDescription','boolean',c3).
attribute(a70,'types','String[]',c7).
attribute(a71,'jjl','JLabel',c7).
attribute(a72,'jl','JLabel',c7).
attribute(a73,'okjb','JButton',c7).
attribute(a74,'cajb','JButton',c7).
attribute(a75,'n','Main',c8).
attribute(a76,'f','Fonts',c8).
attribute(a8,'returnVal','int',c4).
attribute(a9,'option','int',c4).
%table(method,[methid,"name","returntype",classid]).
method(m0,'Notepad.About','About',c0).
method(m1,'Notepad.Print','Print',c1).
method(m10,'Notepad.ExampleFileFilter','ExampleFileFilter',c3).
method(m11,'Notepad.ExampleFileFilter','ExampleFileFilter',c3).
method(m12,'Notepad.ExampleFileFilter','ExampleFileFilter',c3).
method(m13,'Notepad.ExampleFileFilter','ExampleFileFilter',c3).
method(m14,'Notepad.ExampleFileFilter','ExampleFileFilter',c3).
method(m15,'addExtension','ExampleFileFilter',c3).
method(m16,'getDescription','ExampleFileFilter',c3).
method(m17,'setDescription','ExampleFileFilter',c3).
method(m18,'setExtensionListInDescription','ExampleFileFilter',c3).
method(m19,'isExtensionListInDescription','ExampleFileFilter',c3).
method(m2,'printComponent','Print',c1).
method(m20,'accept','ExampleFileFilter',c3).
method(m21,'getExtension','ExampleFileFilter',c3).
method(m22,'Notepad.Actions','Actions',c4).
method(m23,'neW','Actions',c4).
method(m24,'opeN','Actions',c4).
method(m25,'savE','Actions',c4).
method(m26,'prinT','Actions',c4).
method(m27,'exiT','Actions',c4).
method(m28,'fonT','Actions',c4).
method(m29,'abouT','Actions',c4).
method(m3,'disableDoubleBuffering','Print',c1).
method(m30,'cuT','Actions',c4).
method(m31,'copY','Actions',c4).
method(m32,'pastE','Actions',c4).
method(m33,'selectALL','Actions',c4).
method(m34,'finD','Actions',c4).
method(m35,'findNexT','Actions',c4).
method(m36,'lineWraP','Actions',c4).
method(m37,'saveAs','Actions',c4).
method(m38,'save','Actions',c4).
method(m39,'open','Actions',c4).
method(m4,'enableDoubleBuffering','Print',c1).
method(m40,'Notepad.RedoAction','RedoAction',c5).
method(m41,'actionPerformed','RedoAction',c5).
method(m42,'update','RedoAction',c5).
method(m43,'Notepad.Main','Main',c6).
method(m44,'getLineWrap','Main',c6).
method(m45,'getTextArea','Main',c6).
method(m46,'main','Main',c6).
method(m47,'Notepad.Fonts','Fonts',c7).
method(m48,'font','Fonts',c7).
method(m49,'getOkjb','Fonts',c7).
method(m5,'print','Print',c1).
method(m50,'getCajb','Fonts',c7).
method(m51,'access$000','Fonts',c7).
method(m52,'access$200','Fonts',c7).
method(m53,'access$100','Fonts',c7).
method(m54,'Notepad.Center','Center',c8).
method(m55,'Notepad.Center','Center',c8).
method(m56,'nCenter','Center',c8).
method(m57,'fCenter','Center',c8).
method(m6,'print','Print',c1).
method(m7,'Notepad.UndoAction','UndoAction',c2).
method(m8,'actionPerformed','UndoAction',c2).
method(m9,'update','UndoAction',c2).
%table(parameter,[paramid,"type",methid]).
parameter(p0,'Component',m1).
parameter(p1,'Component',m2).
parameter(p10,'String',m12).
parameter(p11,'String',m12).
parameter(p12,'String[]',m13).
parameter(p13,'String[]',m14).
parameter(p14,'String',m14).
parameter(p15,'String',m15).
parameter(p16,'String',m17).
parameter(p17,'boolean',m18).
parameter(p18,'File',m20).
parameter(p19,'File',m21).
parameter(p2,'Component',m3).
parameter(p20,'Main',m22).
parameter(p21,'Main',m40).
parameter(p22,'ActionEvent',m41).
parameter(p23,'String[]',m46).
parameter(p24,'Fonts',m51).
parameter(p25,'Fonts',m52).
parameter(p26,'Fonts',m53).
parameter(p27,'Main',m54).
parameter(p28,'Fonts',m55).
parameter(p3,'Component',m4).
parameter(p4,'Graphics',m6).
parameter(p5,'PageFormat',m6).
parameter(p6,'int',m6).
parameter(p7,'Main',m7).
parameter(p8,'ActionEvent',m8).
parameter(p9,'String',m11).
