%table(class,[classid,"name","fields","methods",superid]).
class(c0,"Main").
class(c1,"klass").
class(c2,"connection").
%table(attribute,[attrid,"name","type",classid]).
attribute(a0,'gen','String',c0).
attribute(a1,'comp','String',c0).
attribute(a10,'apost','String',c0).
attribute(a11,'lineCount','int',c0).
attribute(a12,'line','String',c0).
attribute(a13,'original','String',c0).
attribute(a14,'name1','String',c0).
attribute(a15,'end1','String',c0).
attribute(a16,'role1','String',c0).
attribute(a17,'name2','String',c0).
attribute(a18,'end2','String',c0).
attribute(a19,'role2','String',c0).
attribute(a2,'agg','String',c0).
attribute(a20,'array1','String[]',c0).
attribute(a21,'array2','String[]',c0).
attribute(a22,'klassS','HashMap',c0).
attribute(a23,'connectionS','LinkedList',c0).
attribute(a24,'kounter','int',c0).
attribute(a25,'out','PrintStream',c0).
attribute(a26,'comma','String',c1).
attribute(a27,'quote','String',c1).
attribute(a28,'id','String',c1).
attribute(a29,'name','String',c1).
attribute(a3,'none','String',c0).
attribute(a30,'fields','String',c1).
attribute(a31,'methods','String',c1).
attribute(a32,'quote','String',c2).
attribute(a33,'comma','String',c2).
attribute(a34,'name1','String',c2).
attribute(a35,'role1','String',c2).
attribute(a36,'end1','String',c2).
attribute(a37,'name2','String',c2).
attribute(a38,'role2','String',c2).
attribute(a39,'end2','String',c2).
attribute(a4,'arrow1','String',c0).
attribute(a5,'arrow2','String',c0).
attribute(a6,'comma','String',c0).
attribute(a7,'commaApost','String',c0).
attribute(a8,'apostComma','String',c0).
attribute(a9,'equals','String',c0).
%table(method,[methid,"name","returntype",classid]).
method(m0,'yparser.Main','Main',c0).
method(m1,'main','Main',c0).
method(m10,'dump','connection',c2).
method(m2,'err','Main',c0).
method(m3,'checkNameStructure','Main',c0).
method(m4,'printArray','Main',c0).
method(m5,'yparser.klass','klass',c1).
method(m6,'yparser.klass','klass',c1).
method(m7,'dump','klass',c1).
method(m8,'toId','klass',c1).
method(m9,'yparser.connection','connection',c2).
%table(parameter,[paramid,"type",methid]).
parameter(p0,'String[]',m1).
parameter(p1,'String',m2).
parameter(p10,'String',m9).
parameter(p11,'String',m9).
parameter(p12,'String',m9).
parameter(p13,'String',m9).
parameter(p14,'String',m9).
parameter(p15,'String',m9).
parameter(p2,'String',m3).
parameter(p3,'String',m4).
parameter(p4,'String[]',m4).
parameter(p5,'String[]',m5).
parameter(p6,'String',m6).
parameter(p7,'String',m6).
parameter(p8,'String',m6).
parameter(p9,'String',m8).
